let one = document.getElementById("elzero");
let two = document.getElementsByClassName("element");
let three = document.getElementsByTagName("div");
let four = document.querySelector("div");
let five = document.querySelector("#elzero");
let six = document.querySelector(".element");
let seven = document.querySelector("[name='js']");
let eight = document.querySelectorAll("div");
let nine = document.querySelectorAll(".element");
let ten = document.querySelectorAll("#elzero");
let eleven = document.querySelectorAll("[name='js']");
let twelve = document.body.children[0];
let thirteen = document.body.firstElementChild;
let forteen = document.body.childNodes[0];
let fifteen = document.body.firstChild;

console.log(one);
console.log(two);
console.log(three);
console.log(four);
console.log(five);
console.log(six);
console.log(seven);
console.log(eight);
console.log(nine);
console.log(ten);
console.log(eleven);
console.log(twelve);
console.log(thirteen);
console.log(forteen);
console.log(fifteen);